"""add seller_id

Revision ID: c2486afd0d9d
Revises: c3f5b1a2d441
Create Date: 2026-07-21 18:44:47.154987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2486afd0d9d'
down_revision: Union[str, Sequence[str], None] = 'c3f5b1a2d441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'CANCELED', name='orderstatus'),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CUSTOMER', 'SELLER', 'ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CUSTOMER', 'SELLER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'CANCELED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
